version: "2"
services:
  frontend:
    container_name: frontend
    build: ./bestanden/frontend
    ports:
      - "80:8080"
    restart: always
  backend:
    depends_on:
      - mysql
    container_name: backend
    build: ./bestanden/backend
    ports:
      - "9000:8000"
    command: /bin/bash -c "python manage.py collectstatic --noinput --settings=fipsim.settings.testing && python manage.py migrate --settings=fipsim.settings.testing && python manage.py runserver 0.0.0.0:8000  --settings=fipsim.settings.testing"
    restart: always
  mysql:
    container_name: mysql
    build: ./bestanden/db/
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always

