# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='', max_length=100)),
                ('electric', models.BooleanField(default=False)),
                ('speed', models.IntegerField(default=0)),
                ('lease_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BikeBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CalculationParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsz', models.FloatField(default=0.1307)),
                ('woon_werkverkeer_auto', models.FloatField(default=0.3412)),
                ('woon_werkverkeer_fiets', models.FloatField(default=0.22)),
                ('woon_werkverkeer_auto_belast_vrij', models.IntegerField(default=380)),
                ('co2_gasoline', models.IntegerField(default=107)),
                ('co2_diesel', models.IntegerField(default=89)),
                ('max_vaa_car', models.IntegerField(default=1260)),
                ('tax_decrease_multiplier_werkbonus', models.FloatField(default=0.2803)),
                ('pension_rent_multiplier', models.FloatField(default=0.2)),
                ('high_income_boundary', models.IntegerField(default=7500)),
                ('arbeider_rsz_multiplier', models.FloatField(default=1.08)),
                ('bediende_rsz_multiplier', models.FloatField(default=1)),
                ('tax_decrease_old_family_member', models.IntegerField(default=70)),
                ('tax_decrease_family_member', models.IntegerField(default=34)),
                ('tax_decrease_handicapped', models.IntegerField(default=34)),
                ('high_income_base_tax_scale1', models.FloatField(default=3287.26)),
                ('high_income_multiplier_of_diff', models.FloatField(default=0.535)),
                ('high_income_rent_boundary', models.IntegerField(default=130)),
                ('high_income_base_tax_scale2', models.FloatField(default=2922.79)),
                ('tax_decrease_child1', models.IntegerField(default=34)),
                ('tax_decrease_child2', models.IntegerField(default=93)),
                ('tax_decrease_child3', models.IntegerField(default=248)),
                ('tax_decrease_child4', models.IntegerField(default=454)),
                ('tax_decrease_child5', models.IntegerField(default=671)),
                ('tax_decrease_child6', models.IntegerField(default=887)),
                ('tax_decrease_child7', models.IntegerField(default=1104)),
                ('tax_decrease_child8', models.IntegerField(default=1337)),
                ('tax_decrease_child8plus_multiplier', models.IntegerField(default=241)),
                ('tax_decrease_single', models.IntegerField(default=24)),
                ('tax_decrease_widow_or_unmarried_with_children', models.IntegerField(default=34)),
                ('tax_decrease_married_partner_low_income', models.IntegerField(default=108)),
                ('tax_decrease_married_partner_low_rent', models.IntegerField(default=216)),
                ('low_income_boundary', models.FloatField(default=2370.74)),
                ('tax_decrease_low_income', models.FloatField(default=6.46)),
                ('work_bonus_lowest_boundary', models.FloatField(default=1577.89)),
                ('work_bonus_highest_boundary', models.FloatField(default=2461.27)),
                ('tax_decrease_work_bonus_arbeider_lowest', models.FloatField(default=209.29)),
                ('tax_decrease_work_bonus_arbeider_multiplier_diff', models.FloatField(default=0.2369)),
                ('tax_decrease_work_bonus_bediende_lowest', models.FloatField(default=193.79)),
                ('tax_decrease_work_bonus_bediende_multiplier_diff', models.FloatField(default=0.2194)),
                ('bijzondere_bijdrage_sz_lowest_boundary_np', models.FloatField(default=1095.1)),
                ('bijzondere_bijdrage_sz_lowest_boundary', models.FloatField(default=1945.38)),
                ('bijzondere_bijdrage_sz_married_and_income', models.FloatField(default=9.3)),
                ('bijzondere_bijdrage_sz_middle_boundary', models.FloatField(default=2190.18)),
                ('bijzondere_bijdrage_sz_multiplier_middle_cat', models.FloatField(default=0.076)),
                ('bijzondere_bijdrage_sz_middle_cat_max_value', models.FloatField(default=18.6)),
                ('bijzondere_bijdrage_sz_middle_cat_min_value', models.FloatField(default=9.3)),
                ('bijzondere_bijdrage_sz_high_boundary', models.FloatField(default=6038.83)),
                ('bijzondere_bijdrage_sz_multiplier_high_cat', models.FloatField(default=0.011)),
                ('bijzondere_bijdrage_sz_high_cat_max_value', models.FloatField(default=51.64)),
                ('bijzondere_bijdrage_sz_highest_cat_scale1', models.FloatField(default=60.94)),
                ('percentage_prive_usage_bike', models.FloatField(default=0.2)),
                ('hospitalisation_partner', models.FloatField(default=175)),
                ('hospitalisation_child', models.FloatField(default=68)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='', max_length=100)),
                ('engine_type', models.CharField(default='', max_length=20)),
                ('lease_price', models.FloatField(default=0)),
                ('co2', models.IntegerField(default=0)),
                ('catalog_value', models.FloatField(default=0)),
                ('registration_year', models.DateField()),
                ('image_url', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Category 1'), (2, 'Category 2'), (3, 'Category 3')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='', max_length=100)),
                ('catalog_value', models.IntegerField(default=0)),
                ('device_type', models.CharField(choices=[('S', 'Smartphone'), ('L', 'Laptop'), ('T', 'Tablet')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TechBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tech',
            name='brand',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TechBrand'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CarBrand'),
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CarCategory'),
        ),
        migrations.AddField(
            model_name='bike',
            name='brand',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.BikeBrand'),
        ),
    ]
