# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationparameter',
            name='id',
            field=models.AutoField(auto_created=True, default=2016, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
