# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170113_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationparameter',
            name='vaa_smartphone',
            field=models.IntegerField(default=12.5),
        ),
    ]
