# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_calculationparameter_vaa_smartphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationparameter',
            name='vaa_laptop',
            field=models.IntegerField(default=15),
        ),
    ]
