# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170113_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationparameter',
            name='vaa_internet',
            field=models.IntegerField(default=5),
        ),
    ]
