# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_calculationparameter_vaa_internet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bike',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='calculationparameter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
