# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170118_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bruto', models.FloatField()),
                ('scale1', models.FloatField()),
                ('scale2', models.FloatField()),
            ],
        ),
    ]
