# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170120_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationparameter',
            name='car_cat1_lease',
            field=models.FloatField(default=435),
        ),
        migrations.AddField(
            model_name='calculationparameter',
            name='car_cat2_lease',
            field=models.FloatField(default=485),
        ),
        migrations.AddField(
            model_name='calculationparameter',
            name='car_cat3_lease',
            field=models.FloatField(default=585),
        ),
    ]
