export const strings = {
    en: {
        //universal
        plhInEuro: 'in €',
        plhInGpK: 'in g/km',
        plhPeopleAmount:'no. of people',
        plhSelect: 'pick an option',
        plhPrice: 'price:',
        //income
        incomeBoxTitle: 'family info',
        lblWageBT: 'gross salary',
        ttWageBT: 'The aggregate amount of wages you receive on a regular basis, usually monthly prior to any deductions such as federal and state taxes.',
        lblWorkStatus:'statute',
        ttWorkStatus:'The state of your employment.',
        descWorker:'worker',
        descClerk:'employee',
        lblMaritalStatus: 'marital status',
        ttMaritalStatus: "Marital status, is any of several distinct options that describe a persons relationship with a significant other.",
        lblPartnerWage:'partner gross salary',
        ttPartnerWage:'The gross salary your partner earns every month.',
        descSingle: 'single',
        descCouple: 'living together',
        descMarried: 'married',
        lblPartnerRetirement:'partner retirement',
        ttPartnerRetirement:'If your partner stops working permanently, check this box.',
        lblPartnerHandicapped:'disabled partner',
        ttPartnerHandicapped:'If your partner has a disability or disadvantage that severely limits (but does not prevent) the successful performance of a task or achievement of an objective.',
        lblChildren:'children',
        ttChildren:'Number of dependent children in the family.',
        lblChildrenHandicapped:'',
        ttChildrenHandicapped:'Number of dependent disabled children.',
        lblAdults:'adult',
        ttAdults:'Number of dependent adults in the family',
        lblAdultsHandicapped:'',
        ttAdultsHandicapped:'Number of dependent disabled adults, EXCEPT the partner.',
        lblOld:'65+',
        ttOld:'Number of dependent elderly (65+).',
        lblOldHandicapped:'',
        ttOldHanicapped:'Number of dependent disabled elderly (65+).',

        //mobility
        mobilityBoxTitle: 'mobility',
        descNone: 'none',
        lblTabNothing: 'none',
        lblTabCar: 'car',
        lblTabBicycle: 'bicycle',
        lblTabAllowance: 'allowance',
        ttTabNothing: 'none',
        ttTabCar: 'car',
        ttTabBicycle: 'bicycle',
        ttTabAllowance: 'allowance',
        lblCarLeasePrice: 'lease price',
        ttCarLeasePrice: 'The lease price of the car.',
        lblCarPrice: 'catalog value',
        ttCarPrice: 'The catalog value of the car (with options and taxes).',
        lblCarCo2: 'CO2 (g/km)',
        ttCarCo2: 'The CO2 emission of the car.',
        lblCarFuel: 'fuel type',
        ttCarFuel: 'The fuel type of the car.',
        lblCarFilterCategory: 'category',
        ttCarFilterCategory: 'Filter on the leasing category in which the car is situated.',
        lblCarFilterBrand: 'brand',
        ttCarFilterBrand:'Filter on the brand of the car.',
        lblCarFilterFuel: 'fuel',
        ttCarFilterFuel: 'Filter on the fuel type of the car.',
        descDiesel: 'diesel',
        descPetrol: 'petrol',
        descElectric: 'electric',
        btnCar:'pick a car',
        lblBikeLeasePrice: 'lease price',
        ttBikeLeasePrice: 'The lease price of the bike.',
        btnBike:'pick a bicycle',
        lblBikeFilterBrand:'Brand',
        ttBikeFilterBrand:'Filter on the brand of the bike.',
        lblBikeFilterPrice:'Price',
        ttBikeFilterPrice:'Filter on the lease price of the bike',
        lblAllowanceDistance:'travel distance to work (outward journey)',
        ttAllowanceDistance:'The distance you have to travel from your home to work. Only outward journey!',
        plhAllowanceDistance:'in km',
        lblAllowanceDays:'workdays/week',
        ttAllowanceDays:'The workdays per week you go to work with the car.',

        //Technology
        technologieBoxTitle:'technology',
        lblSmartphone:'smartphone',
        ttSmartphone:'The value of the chosen smartphone.',
        lblMultimedia:'multimedia',
        ttMultimedia:'The value of the chosen multimedia (tablet, smartwatch,...).',
        lblLaptop:'laptop',
        ttLaptop:'The value of the chosen laptop.',
        lblInternet:'internet',
        ttInternet:'The value of the chosen internet subscription.',
        descInternetAll:'Select one',
        descInternet25:'€25 /month',
        descInternet35:'€35 /month',
        descInternet45:'€45 /month',

        //Social security
        socialBoxTitle:'social security',
        lblInsurance:'hospital insurance',
        ttInsurance:'a health insurance plan providing coverage for hospital confinement due to illness, accidents, intensive care of convalescence. Please select the window(s) for the relevant persons.',
        lblInsurancePartner:'partner',
        ttInscurancePartner:'If you want a hospital insurance for your partner, check this window.',
        lblInsuranceChild:'children',
        ttInsuranceChild:'Enter the amount of children you want to get a hospital insurance for.',
        lblRetirement:'retirement contribution',
        ttRetirement:'The money put into your retirement plan.',
        lblChildBenefits:'child benefits',
        ttChildBenefits:"if you're approved by the goverment to claim child benefits, check this window. ",
        lblCharity:'give to charity',
        ttCharity:'Amount of money you want to donate charity. Maximum 100 euro.',
        descMonth:'€78 /month',
        descYear:'€940 /year',

        charityBoxTitle:'charity',
        //result
        resultBoxTitle: 'result',
        ttlBudgetSplit: 'budget allocation',
        ttlValueWithFip: 'with Flex Income Plan',
        ttlValueNoFip: 'without Flex Income Plan',
        lblResultNetMonth: 'net salary',
        ttResultNetMonth: 'Your monthly salary.',
        lblSpentOnSocial: 'social security',
        ttSpentOnSocial: '',
        lblSpentOnMobility: 'mobility',
        ttSpentOnMobility: 'Total budget spent on the mobility module of the flexible income plan.',
        lblSpentOnTechnology: 'technology',
        ttSpentOnTechnology: 'Total budget spent on the technology module of the flexible income plan.',
        lblSpentOnCharity: 'charity',
        ttSpentOnCharity: 'Total budget donated to charity.',
        lblBudgetTotal: 'total budget',
        ttBudgetTotal: 'The total budget used for the calculation of the flexible income plan modules.',
        lblBudgetLeft: 'unspent budget',
        ttBudgetLeft: 'Total unspent budget.',
        lblResultValue: 'received value',
        ttResultValue: 'Result of all the advantages you gain with the flexible income plan.',
        lblWithoutValue: 'value without FIP',
        ttResultValue: 'The result if you weren\'t using the flexible income plan.',
        warningOverspending: 'You\'re spending more than your budget allows.',
        btnResult: 'calculate',

        strNetWageYear: 'net earnings a year',
        strLaptop: 'laptop',
        strBicycle: 'bicycle',
        strCar: 'car',
        strSocialSecurity: 'social security',
        strInternet: 'internet',
        strSmartphone: 'smartphone',
        strAllowance: 'allowance',
        strMultimedia: 'multimedia',
        strCharity: 'charity',

        strBicycleValue: 'care-free bike ownership',
        strCarValue: 'care-free car ownership ',
        strCharityValue: 'warm fuzzy feeling',
        strSocialValue: 'feeling of assurance',
        strTotal: 'total',
        strTotalExtra: 'benefits',
        strAnd: 'and',
    },

    //placeholder as an example, we'll translate when we are ready with the app itself
    nl: {
        //universal
        plhInEuro: 'in €',
        plhInGpK: 'in g/km',
        plhPeopleAmount:'aantal personen',
        plhSelect: 'selecteer een optie',
        plhPrice: 'prijs:',

        //income
        incomeBoxTitle: 'gezinsinkomen',
        lblWageBT: 'brutoloon',
        ttWageBT: 'Het loon inclusief alle bedragen die je aan belastingen en premies moet betalen.',
        lblWorkStatus:'statuut',
        ttWorkStatus:'De staat van uw tewerkstelling.',
        descWorker:'arbeider',
        descClerk:'bediende',
        lblMaritalStatus: 'burgerlijke staat',
        ttMaritalStatus: 'Rechtstoestand van een persoon ten aanzien van een andere persoon.',
        lblPartnerWage:'nettoloon partner',
        ttPartnerWage:'Het maandelijks nettoloon van uw partner.',
        descSingle: 'alleenstaand',
        descCouple: 'samenwonend',
        descMarried: 'gehuwd',
        lblPartnerRetirement:'partnerpensioen',
        ttPartnerRetirement:'Als uw partner permanent gestopt is met werken, vink dit venster aan.',
        lblPartnerHandicapped:'mindervalide partner',
        ttPartnerHandicapped:'Als uw partner mindervalide is, vink dit venster aan.',
        lblChildren:'kinderen',
        ttChildren:'Aantal kinderen in uw gezin die u ten laste heeft.',
        lblChildrenHandicapped:'',
        ttChildrenHandicapped:'Het aantal mindervalide kinderen in uw gezin die u ten laste heeft.',
        lblAdults:'volwassenen',
        ttAdults:'Het aantal volwassenen in uw gezin die u ten laste heeft.',
        lblAdultsHandicapped:'',
        ttAdultsHandicapped:'Het aantal mindervalide volwassenen in uw gezin die u ten laste heeft. UITGEZONDERD uw partner.',
        lblOld:'senioren (65+)',
        ttOld:'Het aantal personen ouder dan 65 jaar in uw gezin die u ten laste heeft.',
        lblOldHandicapped:'',
        ttOldHanicapped:'Het aantal mindervalide personen ouder dan 65 jaar in uw gezin die u ten laste heeft.',

        //mobility
        mobilityBoxTitle: 'mobiliteit',
        descNone: 'geen',
        lblTabNothing: 'geen',
        lblTabCar: 'auto',
        lblTabBicycle: 'fiets',
        lblTabAllowance: 'woon-werk',
        ttTabNothing: 'geen',
        ttTabCar: 'auto',
        ttTabBicycle: 'fiets',
        ttTabAllowance: 'woon-werk',
        lblCarLeasePrice: 'leaseprijs',
        ttCarLeasePrice: 'De leaseprijs van de gekozen auto.',
        lblCarPrice: 'cataloguswaarde',
        ttCarPrice: 'De cataloguswaarde van de gekozen auto (inclusief opties en btw).',
        lblCarCo2: 'CO2 (g/km)',
        ttCarCo2: 'De CO2 uitstoot van de gekozen auto.',
        lblCarFuel: 'type brandstof',
        ttCarFuel: 'Het type brandstof van de gekozen auto.',
        lblCarFilterCategory: 'categorie',
        ttCarFilterCategory: 'Filter op de leasecategorie waaronder de auto valt.',
        lblCarFilterBrand: 'merk',
        ttCarFilterBrand:'Filter op het merk van de auto.',
        lblCarFilterFuel: 'brandstof',
        ttCarFilterFuel: 'Filter op het type brandstof die de auto gebruikt.',
        descDiesel: 'diesel',
        descPetrol: 'benzine',
        descElectric: 'elektrisch',
        btnCar:'selecteer een auto',
        lblBikeLeasePrice: 'leaseprijs',
        ttBikeLeasePrice: 'De leaseprijs van de gekozen fiets.',
        btnBike:'selecteer een fiets',
        lblBikeFilterBrand:'merk',
        ttBikeFilterBrand:'Filter op het merk van de fiets.',
        lblBikeFilterPrice:'prijs',
        ttBikeFilterPrice:'Filter op de prijs van de fiets.',
        lblAllowanceDistance:'afstand woon-werk (enkel)',
        ttAllowanceDistance:'De afstand van uw huis tot het werk, dit is enkel heenreis.',
        plhAllowanceDistance:'in km',
        lblAllowanceDays:'werkdagen/week',
        ttAllowanceDays:'Het aantal werkdagen per week waarmee u met de auto opgaat.',

        //technologie
        technologieBoxTitle:'technologie',
        lblSmartphone:'smartphone',
        ttSmartphone:'De prijs van de gekozen smartphone.',
        lblMultimedia:'multimedia',
        ttMultimedia:'De prijs van de gekozen multimedia (tablet, smartwatch,...).',
        lblLaptop:'laptop',
        ttLaptop:'De prijs van de gekozen laptop.',
        lblInternet:'internet',
        ttInternet:'De prijs van het gekozen internet abonnement. Wanneer uw bedrag niet overeenkomt selecteert u het bedrag dat het dichtste onder uw factuur ligt.',
        descInternetAll:'Selecteer een optie',
        descInternet25:'€25 /maand',
        descInternet35:'€35 /maand',
        descInternet45:'€45 /maand',

        //social security
        socialBoxTitle:'sociale bescherming',
        lblInsurance:'hospitalisatieverzekering',
        ttInsurance:'Een aanvullende verzekering voor onverwachte ziekenhuiskosten en ziekenhuisdekking.',
        lblInsurancePartner:'partner',
        ttInscurancePartner:'Als u een hospitalisatieverzekering voor uw partner wilt verkrijgen, vink dit venster aan.',
        lblInsuranceChild:'kind(eren)',
        ttInsuranceChild:'Als u een hospitalisatieverzekering voor uw kind(eren) wilt verkrijgen, vink dit venster aan.',
        lblRetirement:'pensioensparen',
        ttRetirement:'Een aanvullend pensioen plan opbouwen, door maandelijks een storting te doen. Indien dit gewenst is, gelieve dit venser aan te vinken.',
        lblChildBenefits:'kinderbijslag',
        ttChildBenefits:'Een uitkering van de overheid voor ouders, als tegemoetkoming in de kosten van hun kinderen. Wanneer u dit kan vorderen, gelieve dit venster aan te vinken.',
        lblCharity:'geef aan een goed doel',
        ttCharity:'Een geldbedrag dat aan het goede doel wordt geschonken. Maximum 100 euro.',
        descMonth:'€78 /maand',
        descYear:'€940 /jaar',

        charityBoxTitle:'goed doel',
        //result
        resultBoxTitle: 'resultaat',
        ttlBudgetSplit: 'budgetverdeling',
        ttlValueWithFip: 'met Flex Income Plan',
        ttlValueNoFip: 'zonder Flex Income Plan',
        lblResultNetMonth: 'netto salaris',
        ttResultNetMonth: 'Uw maandelijkse salaris.',
        lblSpentOnSocial: 'sociale bescherming',
        lblSpentOnMobility: 'mobiliteit',
        ttSpentOnMobility: 'Budget dat gespendeerd wordt aan de mobiliteitsmodule van het flex incomeplan.',
        lblSpentOnTechnology: 'technologie',
        ttSpentOnTechnology: 'Budget dat gespendeerd wordt aan de technologie module van het flexibel inkomplan.',
        lblSpentOnCharity: 'goed doel',
        ttSpentOnCharity: 'Budget dat wordt gedoneert aan het goede doel',
        lblBudgetTotal: 'totaal budget',
        ttBudgetTotal: 'Het totaal budget dat je ter beschikking hebt dankzij het flex incomeplan.',
        lblBudgetLeft: 'resterend budget',
        ttBudgetLeft: 'Het budget dat niet gespendeerd wordt op dit moment.',
        lblResultValue: 'totaalpakket',
        ttResultValue: 'Resultaat van de voordelen die je hebt dankzij het flex incomeplan.',
        lblWithoutValue: 'uitbetaling zonder FIP',
        ttResultValue: 'Het resultaat indien je het flex incomeplan niet zou gebruiken.',
        warningOverspending: 'Uw budget laat het niet toe om zoveel te spenderen aan het Flex Income Plan.',
        btnResult: 'berekenen',

        strNetWageYear: 'netto per jaar',
        strLaptop: 'laptop',
        strBicycle: 'fiets',
        strCar: 'auto',
        strSocialSecurity: 'sociale bescherming',
        strInternet: 'internet',
        strSmartphone: 'smartphone',
        strAllowance: 'woon-werkverkeer vergoeding',
        strMultimedia: 'multimedia',
        strCharity: 'goed doel',

        strBicycleValue: 'fiets ter beschikking',
        strCarValue: 'auto ter beschikking',
        strCharityValue: 'warm goed gevoel',
        strSocialValue: 'gevoel van zekerheid',
        strTotal: 'totaal',
        strTotalExtra: 'voordelen',
        strAnd: 'en',
    }
}